#!/usr/bin/env ruby

begin
  require "rubygems"
  require 'chef'
  require 'highline/import'
  require 'optparse'

  optparse = OptionParser.new

  # Parse the command line.
  optparse.parse!

  runlist = case
    when ARGV[0] == 'update_vhosts'
      runlist = 'run_vhosts.json'
    when ARGV[0] == 'help'
      puts "Usage: megalodon [install|update_vhosts|help]"
      exit
    else
      runlist = 'run_list.json'
  end

  cwd = Dir.pwd
  gem_path = `gem env| grep "EXECUTABLE DIRECTORY"| awk -F': ' '{print $2}'`.strip
  unless File.exists?("#{gem_path}/chef-solo")
    raise "Cannot find chef-solo at #{gem_path}/chef-solo}"
  end

  puts "Copying custom forumulas"
  system("cp #{cwd}/formulas/* /usr/local/Library/Formula/")
  puts "Starting chef-solo run"
  system("#{gem_path}/chef-solo -j #{cwd}/config/#{runlist} -c #{cwd}/config/solo.rb")

rescue LoadError => e
  puts e.message
  puts "You don't seem to have chef, installing it for you"
  sudo = File.writable?(%x[gem environment| grep "INSTALLATION DIRECTORY"| awk -F':' '{print $2}'].strip) ? "" : "sudo "
  system("#{sudo} gem install chef --no-rdoc --no-ri")
  puts "I had to install chef for you, please rerun 'megalodon install'"
end
