#!/usr/bin/env ruby

begin
  require "rubygems"
  require 'chef'
  require 'json'
  require "thor"

  class MegaladonCommand < Thor
    desc "install", "Runs chef-solo"
    def install
      puts "Copying custom forumulas"
      system("cp formulas/* /usr/local/Library/Formula/")
      puts "Starting chef-solo run"
      system("chef-solo -j config/run_list.json -c config/solo.rb")
    end
  end

  MegaladonCommand.start

rescue LoadError => e
  puts e.message
  puts "You don't seem to have chef, installing it for you"
  sudo = File.writable?(%x[gem environment| grep "INSTALLATION DIRECTORY"| awk -F':' '{print $2}'].strip) ? "" : "sudo "
  system("#{sudo} gem install chef --no-rdoc --no-ri")
  puts "I had to install chef for you, please rerun 'megalodon install'"
end
